//  TASC Issue: May 2026
//     Article: A Rolling Autocorrelation Function
//              The AutoTune Filter
//  Article By: John F. Ehlers
//    Language: TradingView's Pine Script® v6
// Provided By: PineCoders, for tradingview.com

//@version=6
indicator("TASC 2026.05 The AutoTune Filter", "AutoTune")

//#region Inputs

enum disp
    F = "Filter"
    M = "Min. Correlation"
    D = "Dominant Cycle"
    B = "Band Pass"

src = input.source(close, "Source:")
window = input.int(20, "Window:")
dispType = input.enum(disp.F, title = "Output:")

//#endregion

//#region Functions

// @function High Pass Filter.
HP(float _src, int _period) =>

    float Q = math.exp(-1.414*math.pi/_period)
    float c1 = 2.0*Q*math.cos(1.414*math.pi/_period)
    float c2 = Q*Q
    float a0 = (1 + c1 + c2)/4
    float hp = 0.0
    if bar_index >= 4
        hp := a0*(_src - 2*_src[1] + 
              _src[2]) + c1*hp[1] - c2*hp[2]
    hp

// @function Bandpass
BP(float _src = close, 
   int _period = 20, 
   float _bandwidth=0.25) =>

    float L1 = math.cos(2.0*math.pi/_period)
    float G1 = math.cos(_bandwidth*2.0*math.pi/_period)
    float S1 = 1.0/G1 - math.sqrt(1.0/(G1*G1) - 1.0)
    float BP = 0.0
    
    BP := 0.5*(1.0 - S1)*(_src - _src[2]) + 
     L1*(1.0 + S1)*nz(BP[1]) - S1*nz(BP[2])
    
    if bar_index < 3
        BP := 0.0
    BP

// @function AutoTune Filter.
AF(float _src = close, 
   int _window = 20, 
   float _bandwidth=0.25) =>

    array<float> Corr = array.new<float>(100)
    float Filt = HP(_src, _window)
    // Correlation
    for lag = 1 to _window
        float Sx = 0.0
        float Sy = 0.0
        float Sxx = 0.0
        float Sxy = 0.0
        float Syy = 0.0
        for J = 0 to _window - 1
            float X = Filt[J]
            float Y = Filt[lag + J]
            Sx += X
            Sy += Y
            Sxx += X*X
            Sxy += X*Y
            Syy += Y*Y
        if ((_window*Sxx - Sx*Sx) > 0.0) and 
         ((_window*Syy - Sy*Sy) > 0.0)
            
            Corr.set(lag, 
            (_window*Syy - Sy*Sy)/math.sqrt(
             (_window*Sxx - Sx*Sx)*(_window*Syy - Sy*Sy)))
    
    float MinCorr = 1.0
    int DC = 0
    for lag = 1 to _window
        if Corr.get(lag) < MinCorr
            MinCorr := Corr.get(lag)
            DC := 2*lag
    if DC > DC[1] + 2
        DC := DC[1] + 2
    if DC < DC[1] - 2
        DC := DC[1] - 2
    
    float BP = BP(_src, DC, _bandwidth)
    [Filt, MinCorr, DC, BP]

//#endregion

//#region Calc

[f, mc, dc, bp] = AF(src, window)

//#endregion

//#region Display

float show_disp = switch
    dispType == disp.F => f
    dispType == disp.M => mc
    dispType == disp.D => dc
    dispType == disp.B => bp

hline(0, title = "Zero")
plot(show_disp, title = "Display")

//#endregion