//  TASC Issue: February 2025
//     Article: Drunkard's Walk:
//              Theory And Measurement By Autocorrelation.
//  Article By: John F. Elhers
//    Language: TradingView's Pine Script™ v5
// Provided By: PineCoders, for tradingview.com


//@version=5
title ='TASC 2025.02 Autocorrelation Indicator'
stitle = 'ACI'
indicator(title, stitle, false)


// --- Inputs and Constants ---


//@enum Range Selection Enumeration:
enum R
    R1 = '0 -> 32'
    R2 = '33 -> 65'
    R3 = '66 -> 98'


// @variable Full Angle Rotation `360`.
float FROT = 2.0 * math.pi
// @variable Square Root of 2 `1.414`.
float SQRT2 = math.sqrt(2.0)
// @variable Perfect Cycle Test signal.
// `Signal = math.sin(360.0 * bar_index / 30.0)`.
float TS = math.sin(FROT * bar_index / 30.0)


float Src  = input.source(close, 'Source:')
int Length = input.int(100, 'Length:')
// @variable Use Test Signal.
bool iTest = input.bool(false, 'Use Test Signal:')
// @variable Range Selection.
R iR = input.enum(R.R1, 'Range Selection:')


// --- Functions ---


// @function      UltimateSmoother 
UltimateSmoother (float src, int period) =>
    float a1 = math.exp(-1.414 * math.pi / period)
    float c2 = 2.0 * a1 * math.cos(1.414 * math.pi / period)
    float c3 = -a1 * a1
    float c1 = (1.0 + c2 - c3) / 4.0
    float us = src
    if bar_index >= 4
        us := (1.0 - c1) * src + 
              (2.0 * c1 - c2) * src[1] - 
              (c1 + c3) * src[2] + 
              c2 * nz(us[1]) + c3 * nz(us[2])
    us


// @function Correlation
correlation (float src, int length) =>
    float[] _corr = array.new<float>(101, 0.0)
    color[] _col = array.new<color>(101, #00000000)
    for _l = 0 to 99
        float _Sx = 0.0
        float _Sy = 0.0
        float _Sxx = 0.0
        float _Sxy = 0.0
        float _Syy = 0.0
        for _j = 0 to length - 1
            float _x = src[_j]
            float _y = src[_l + _j]
            _Sx += _x
            _Sy += _y
            _Sxx += _x * _x
            _Sxy += _x * _y
            _Syy += _y * _y
        float _ca1 = length * _Sxx - _Sx * _Sx
        float _ca2 = length * _Syy - _Sy * _Sy
        if _ca1 > 0.0 and _ca2 > 0.0
            float _ca3 = length * _Sxy - _Sx * _Sy
            _corr.set(_l + 1, _ca3 / math.sqrt(_ca1 * _ca2))
    for _l = 1 to 99
        float _c = _corr.get(_l + 1)
        if _c >= 0.0
            _col.set(_l, color.rgb(255, 255 * (1.0 - _c), 0))
        if _c < 0.0
            _col.set(_l, color.rgb(255 * (1.0 + _c), 255, 0))
    _col




// --- Calculations: ---


float Filt = iTest ? TS : UltimateSmoother(Src, Length)


//@variable Color array.
color[] C = correlation(Filt, Length)


switch iR
    R.R1 => C := C.slice(0, 32)
    R.R2 => C := C.slice(33, 65)
    => C := C.slice(66, 98)


int IDX00 = iR == R.R1 ? 00 : (iR == R.R2 ? 33+00 : 66+00)
int IDX01 = iR == R.R1 ? 01 : (iR == R.R2 ? 33+01 : 66+01)
int IDX02 = iR == R.R1 ? 02 : (iR == R.R2 ? 33+02 : 66+02)
int IDX03 = iR == R.R1 ? 03 : (iR == R.R2 ? 33+03 : 66+03)
int IDX04 = iR == R.R1 ? 04 : (iR == R.R2 ? 33+04 : 66+04)
int IDX05 = iR == R.R1 ? 05 : (iR == R.R2 ? 33+05 : 66+05)
int IDX06 = iR == R.R1 ? 06 : (iR == R.R2 ? 33+06 : 66+06)
int IDX07 = iR == R.R1 ? 07 : (iR == R.R2 ? 33+07 : 66+07)
int IDX08 = iR == R.R1 ? 08 : (iR == R.R2 ? 33+08 : 66+08)
int IDX09 = iR == R.R1 ? 09 : (iR == R.R2 ? 33+09 : 66+09)
int IDX10 = iR == R.R1 ? 10 : (iR == R.R2 ? 33+10 : 66+10)
int IDX11 = iR == R.R1 ? 11 : (iR == R.R2 ? 33+11 : 66+11)
int IDX12 = iR == R.R1 ? 12 : (iR == R.R2 ? 33+12 : 66+12)
int IDX13 = iR == R.R1 ? 13 : (iR == R.R2 ? 33+13 : 66+13)
int IDX14 = iR == R.R1 ? 14 : (iR == R.R2 ? 33+14 : 66+14)
int IDX15 = iR == R.R1 ? 15 : (iR == R.R2 ? 33+15 : 66+15)
int IDX16 = iR == R.R1 ? 16 : (iR == R.R2 ? 33+16 : 66+16)
int IDX17 = iR == R.R1 ? 17 : (iR == R.R2 ? 33+17 : 66+17)
int IDX18 = iR == R.R1 ? 18 : (iR == R.R2 ? 33+18 : 66+18)
int IDX19 = iR == R.R1 ? 19 : (iR == R.R2 ? 33+19 : 66+19)
int IDX20 = iR == R.R1 ? 20 : (iR == R.R2 ? 33+20 : 66+20)
int IDX21 = iR == R.R1 ? 21 : (iR == R.R2 ? 33+21 : 66+21)
int IDX22 = iR == R.R1 ? 22 : (iR == R.R2 ? 33+22 : 66+22)
int IDX23 = iR == R.R1 ? 23 : (iR == R.R2 ? 33+23 : 66+23)
int IDX24 = iR == R.R1 ? 24 : (iR == R.R2 ? 33+24 : 66+24)
int IDX25 = iR == R.R1 ? 25 : (iR == R.R2 ? 33+25 : 66+25)
int IDX26 = iR == R.R1 ? 26 : (iR == R.R2 ? 33+26 : 66+26)
int IDX27 = iR == R.R1 ? 27 : (iR == R.R2 ? 33+27 : 66+27)
int IDX28 = iR == R.R1 ? 28 : (iR == R.R2 ? 33+28 : 66+28)
int IDX29 = iR == R.R1 ? 29 : (iR == R.R2 ? 33+29 : 66+29)
int IDX30 = iR == R.R1 ? 30 : (iR == R.R2 ? 33+30 : 66+30)
int IDX31 = iR == R.R1 ? 31 : (iR == R.R2 ? 33+31 : 66+31)
int IDX32 = iR == R.R1 ? 32 : (iR == R.R2 ? 33+32 : 66+32)


PLTS = plot.style_line, DSP = display.pane, F = false
plot(IDX01, 'S', C.get(00), 2, PLTS, F, display=DSP)
plot(IDX02, 'S', C.get(01), 2, PLTS, F, display=DSP)
plot(IDX03, 'S', C.get(02), 2, PLTS, F, display=DSP)
plot(IDX04, 'S', C.get(03), 2, PLTS, F, display=DSP)
plot(IDX05, 'S', C.get(04), 2, PLTS, F, display=DSP)
plot(IDX06, 'S', C.get(05), 2, PLTS, F, display=DSP)
plot(IDX07, 'S', C.get(06), 2, PLTS, F, display=DSP)
plot(IDX08, 'S', C.get(07), 2, PLTS, F, display=DSP)
plot(IDX09, 'S', C.get(08), 2, PLTS, F, display=DSP)
plot(IDX10, 'S', C.get(09), 2, PLTS, F, display=DSP)
plot(IDX11, 'S', C.get(10), 2, PLTS, F, display=DSP)
plot(IDX12, 'S', C.get(11), 2, PLTS, F, display=DSP)
plot(IDX13, 'S', C.get(12), 2, PLTS, F, display=DSP)
plot(IDX14, 'S', C.get(13), 2, PLTS, F, display=DSP)
plot(IDX15, 'S', C.get(14), 2, PLTS, F, display=DSP)
plot(IDX16, 'S', C.get(15), 2, PLTS, F, display=DSP)
plot(IDX17, 'S', C.get(16), 2, PLTS, F, display=DSP)
plot(IDX18, 'S', C.get(17), 2, PLTS, F, display=DSP)
plot(IDX19, 'S', C.get(18), 2, PLTS, F, display=DSP)
plot(IDX20, 'S', C.get(19), 2, PLTS, F, display=DSP)
plot(IDX21, 'S', C.get(20), 2, PLTS, F, display=DSP)
plot(IDX22, 'S', C.get(21), 2, PLTS, F, display=DSP)
plot(IDX23, 'S', C.get(22), 2, PLTS, F, display=DSP)
plot(IDX24, 'S', C.get(23), 2, PLTS, F, display=DSP)
plot(IDX25, 'S', C.get(24), 2, PLTS, F, display=DSP)
plot(IDX26, 'S', C.get(25), 2, PLTS, F, display=DSP)
plot(IDX27, 'S', C.get(26), 2, PLTS, F, display=DSP)
plot(IDX28, 'S', C.get(27), 2, PLTS, F, display=DSP)
plot(IDX29, 'S', C.get(28), 2, PLTS, F, display=DSP)
plot(IDX30, 'S', C.get(29), 2, PLTS, F, display=DSP)
plot(IDX31, 'S', C.get(30), 2, PLTS, F, display=DSP)
plot(IDX32, 'S', C.get(31), 2, PLTS, F, display=DSP)
